export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  category: Category;
  image: string;
  images: string[];
  description: string;
  details: string[];
  rating: number;
  reviews: number;
  inStock: number;
  badge?: string;
  exclusive?: boolean;
  cursed?: boolean;
}

export type Category = "timepieces" | "leather-goods" | "automobiles" | "jewelry" | "yachts" | "shoes";

export const CATEGORIES: { id: Category; label: string; icon: string }[] = [
  { id: "timepieces", label: "Timepieces", icon: "⌚" },
  { id: "leather-goods", label: "Leather Goods", icon: "👜" },
  { id: "shoes", label: "Shoes", icon: "👟" },
  { id: "automobiles", label: "Automobiles", icon: "🚗" },
  { id: "jewelry", label: "Jewelry", icon: "💎" },
  { id: "yachts", label: "Yachts & Jets", icon: "⛵" },
];

// All prices in INR (1 USD ≈ ₹95)
export const PRODUCTS: Product[] = [

  // ── TIMEPIECES ─────────────────────────────────────────────────────────────
  {
    id: "rolex-submariner",
    name: "Submariner Date",
    brand: "Rolex",
    price: 13_77_500,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=800&q=90",
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=800&q=90",
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=90",
    ],
    description: "The reference among divers' watches, the Submariner Date has been an icon of refinement and performance since 1953.",
    details: [
      "Oystersteel case, 41mm",
      "Cerachrom bezel in black ceramic",
      "Waterproof to 300 metres",
      "Calibre 3235 movement",
      "5-year international guarantee",
    ],
    rating: 4.9,
    reviews: 2847,
    inStock: 2,
    badge: "Bestseller",
  },
  {
    id: "patek-nautilus",
    name: "Nautilus 5711",
    brand: "Patek Philippe",
    price: 84_55_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=90",
    images: [
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=90",
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=800&q=90",
    ],
    description: "An icon of watchmaking, the Nautilus epitomises the union of elegance and sporting character.",
    details: [
      "Stainless steel, 40mm",
      "Blue dial with horizontal embossed motif",
      "Calibre 26-330 S C",
      "Annual calendar complication",
      "Water resistant to 120 metres",
    ],
    rating: 5.0,
    reviews: 1203,
    inStock: 1,
    badge: "Extremely Rare",
    exclusive: true,
  },
  {
    id: "ap-royal-oak",
    name: "Royal Oak Offshore",
    brand: "Audemars Piguet",
    price: 39_90_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1619134778706-7015533a6150?auto=format&fit=crop&w=800&q=90",
    images: [
      "https://images.unsplash.com/photo-1619134778706-7015533a6150?auto=format&fit=crop&w=800&q=90",
    ],
    description: "Bold, sporty, and instantly recognizable. The Royal Oak Offshore redefines the boundaries of haute horlogerie.",
    details: [
      "Black ceramic case, 44mm",
      "In-house calibre 3126/3840 ST",
      "Chronograph function",
      "Water resistant to 100 metres",
      "Integrated rubber strap",
    ],
    rating: 4.8,
    reviews: 876,
    inStock: 3,
  },
  {
    id: "richard-mille-rm11",
    name: "RM 11-03 Flyback",
    brand: "Richard Mille",
    price: 1_33_00_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1583482183071-71bc07d4d8eb?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1583482183071-71bc07d4d8eb?auto=format&fit=crop&w=800&q=90"],
    description: "The most technically complex wristwatch ever made. Worn by Rafael Nadal on the tennis court. Enough said.",
    details: [
      "Titanium case, 49mm",
      "Calibre RMAC3 movement",
      "Annual calendar + flyback chronograph",
      "Sapphire crystal case back",
      "NTPT carbon dial",
    ],
    rating: 5.0,
    reviews: 432,
    inStock: 1,
    badge: "As Seen on Nadal",
    exclusive: true,
  },
  {
    id: "omega-speedmaster",
    name: "Speedmaster Moonwatch",
    brand: "Omega",
    price: 5_89_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=800&q=90"],
    description: "The watch that went to the Moon in 1969. NASA-certified. Worn by every Apollo astronaut. A legend.",
    details: [
      "42mm stainless steel case",
      "Calibre 3861 Co-Axial",
      "Hesalite crystal",
      "Tachymetre bezel",
      "Black dial",
    ],
    rating: 4.9,
    reviews: 14890,
    inStock: 5,
    badge: "Moon-Certified",
  },
  {
    id: "jaeger-lecoultre-reverso",
    name: "Reverso Tribute Duoface",
    brand: "Jaeger-LeCoultre",
    price: 19_00_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1621835249645-4fa5e3e02b23?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1621835249645-4fa5e3e02b23?auto=format&fit=crop&w=800&q=90"],
    description: "Art Deco made timeless. The Reverso's swivelling case reveals a second dial — two time zones, one masterpiece.",
    details: [
      "Manual winding",
      "Rectangular swivelling case",
      "Two dials — day & night",
      "Calibre 854A/2",
      "Alligator strap",
    ],
    rating: 4.8,
    reviews: 2103,
    inStock: 3,
  },
  {
    id: "vacheron-overseas",
    name: "Overseas Self-Winding",
    brand: "Vacheron Constantin",
    price: 21_85_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1551816230-ef5deaed4a26?auto=format&fit=crop&w=800&q=90"],
    description: "The Overseas embodies the art of travel. In stainless steel with a blue dial, it is the ultimate companion for the global explorer.",
    details: [
      "Stainless steel, 41.5mm",
      "Calibre 5100 manufacture movement",
      "Manufacture-decorated movement",
      "Interchangeable bracelet system",
      "Water resistant to 150 metres",
    ],
    rating: 4.9,
    reviews: 1430,
    inStock: 2,
    badge: "Manufacture Movement",
  },
  {
    id: "cartier-santos",
    name: "Santos-Dumont Large",
    brand: "Cartier",
    price: 7_60_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1615733869173-d847b8e7fccc?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1615733869173-d847b8e7fccc?auto=format&fit=crop&w=800&q=90"],
    description: "Created for aviator Alberto Santos-Dumont in 1904, the Santos is the world's first purpose-built wristwatch. History on your wrist.",
    details: [
      "Steel and yellow gold, 39.9 × 47.5mm",
      "Quartz movement",
      "Iconic exposed screws",
      "SmartLink interchangeable bracelet",
      "Sapphire crystal",
    ],
    rating: 4.8,
    reviews: 5670,
    inStock: 4,
    badge: "Aviation Icon",
  },
  {
    id: "jacob-co-astronomia",
    name: "Astronomia Solar Zodiac",
    brand: "Jacob & Co.",
    price: 4_75_00_000,
    category: "timepieces",
    image: "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=800&q=90"],
    description: "A miniature solar system on your wrist. The Astronomia Solar rotates once every 10 minutes, carrying a hand-painted miniature Sun. This watch doesn't tell time — it transcends it.",
    details: [
      "Triple-axis tourbillon",
      "Hand-painted miniature Sun",
      "Baguette diamond bezel",
      "Movement visible from all sides",
      "1 of 18 pieces worldwide",
    ],
    rating: 5.0,
    reviews: 18,
    inStock: 1,
    badge: "1 of 18",
    exclusive: true,
    cursed: true,
  },

  // ── LEATHER GOODS ──────────────────────────────────────────────────────────
  {
    id: "hermes-birkin",
    name: "Birkin 30",
    brand: "Hermès",
    price: 27_07_500,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=90",
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=90",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=90",
    ],
    description: "The Birkin bag is the ultimate expression of craftsmanship and exclusivity. Each piece is handcrafted by a single artisan.",
    details: [
      "Togo calfskin leather",
      "Gold-plated hardware",
      "Handcrafted in France",
      "Comes with lock, keys & clochette",
      "Certificate of authenticity",
    ],
    rating: 5.0,
    reviews: 4521,
    inStock: 1,
    badge: "Waitlist: 2 Years",
    exclusive: true,
  },
  {
    id: "chanel-255",
    name: "2.55 Reissue",
    brand: "Chanel",
    price: 9_31_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=90"],
    description: "Since 1955, the 2.55 has stood as the most recognizable handbag in the world. Timeless, iconic, forever.",
    details: [
      "Aged calfskin leather",
      "Aged gold-tone metal hardware",
      "Double-chain and leather strap",
      "Size: 25.5cm × 15.5cm × 6.5cm",
      "Made in France",
    ],
    rating: 4.9,
    reviews: 6234,
    inStock: 4,
  },
  {
    id: "lv-keepall",
    name: "Keepall Bandoulière 55",
    brand: "Louis Vuitton",
    price: 3_04_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=90"],
    description: "The quintessential travel companion since 1930. Supple, spacious, and unmistakably Louis Vuitton.",
    details: [
      "Monogram canvas",
      "Cowhide leather trim",
      "Detachable shoulder strap",
      "55cm × 31cm × 26cm",
      "Made in France",
    ],
    rating: 4.7,
    reviews: 8901,
    inStock: 8,
  },
  {
    id: "bottega-veneta-jodie",
    name: "Jodie Intrecciato Bag",
    brand: "Bottega Veneta",
    price: 3_80_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1590650153855-d9e808231d41?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1590650153855-d9e808231d41?auto=format&fit=crop&w=800&q=90"],
    description: "The bag that made logoless luxury cool again. Woven lambskin so soft you'll want to sleep with it.",
    details: [
      "Intrecciato woven lambskin",
      "Knotted handle",
      "Suede lining",
      "One interior slip pocket",
      "Made in Italy",
    ],
    rating: 4.9,
    reviews: 5670,
    inStock: 4,
  },
  {
    id: "saint-laurent-loulou",
    name: "Loulou Small Chain Bag",
    brand: "Saint Laurent",
    price: 2_47_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=90"],
    description: "Edgy, Parisian, and endlessly chic. The Loulou is the bag that goes from gallery opening to après-dinner.",
    details: [
      "Matelassé leather",
      "YSL logo quilting",
      "Gold-tone chain strap",
      "Flap with push-lock closure",
      "Made in Italy",
    ],
    rating: 4.8,
    reviews: 7234,
    inStock: 6,
  },
  {
    id: "celine-classic-box",
    name: "Classic Box Bag",
    brand: "Céline",
    price: 4_56_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=800&q=90"],
    description: "Understated perfection. The Classic Box has been the insider's choice since Phoebe Philo introduced it in 2010.",
    details: [
      "Smooth calfskin",
      "Palladium-finish hardware",
      "Detachable strap",
      "Interior zip pocket",
      "Made in Italy",
    ],
    rating: 4.9,
    reviews: 4102,
    inStock: 2,
    exclusive: true,
  },
  {
    id: "dior-lady-dior",
    name: "Lady Dior Medium",
    brand: "Dior",
    price: 4_75_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=90"],
    description: "Princess Diana's favourite. The Lady Dior's cannage stitching and charm-adorned handles are instantly recognisable worldwide.",
    details: [
      "Cannage lambskin",
      "Gold-tone D.I.O.R. charms",
      "Two handles + removable strap",
      "Zip closure",
      "Made in Italy",
    ],
    rating: 4.9,
    reviews: 8921,
    inStock: 3,
    badge: "Princess Diana's Choice",
  },
  {
    id: "fendi-baguette",
    name: "Baguette Nappa Bag",
    brand: "Fendi",
    price: 2_85_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1614179818511-83c3cf6cf6c4?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1614179818511-83c3cf6cf6c4?auto=format&fit=crop&w=800&q=90"],
    description: "The bag that launched a thousand imitations. Made iconic by Sex and the City. Now in your virtual wardrobe.",
    details: [
      "Nappa leather",
      "FF logo baguette clasp",
      "Single shoulder strap",
      "Suede lining",
      "Made in Italy",
    ],
    rating: 4.7,
    reviews: 12540,
    inStock: 5,
  },
  {
    id: "prada-re-edition",
    name: "Re-Edition 2005 Bag",
    brand: "Prada",
    price: 1_62_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=90"],
    description: "The nylon bag that started a fashion revolution — twice. Prada's Re-Edition is the coolest bag on any street.",
    details: [
      "Re-Nylon fabric",
      "Saffiano leather trim",
      "Magnetic snap closure",
      "Adjustable strap",
      "Made in Italy",
    ],
    rating: 4.8,
    reviews: 18320,
    inStock: 8,
  },
  {
    id: "goyard-st-louis",
    name: "St. Louis PM Tote",
    brand: "Goyard",
    price: 1_90_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1548036341-3d6d0e6e25e5?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1548036341-3d6d0e6e25e5?auto=format&fit=crop&w=800&q=90"],
    description: "The ultimate flex for those who know. No logo on the outside — just the iconic Goyardine coated canvas that says everything without saying anything.",
    details: [
      "Goyardine coated canvas",
      "Leather trim handles",
      "Removable zip pouch",
      "Lightweight structure",
      "Handmade in Paris",
    ],
    rating: 4.8,
    reviews: 3210,
    inStock: 5,
    badge: "No Logo Needed",
  },
  {
    id: "loewe-puzzle",
    name: "Puzzle Small Bag",
    brand: "Loewe",
    price: 2_47_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4b4357?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4b4357?auto=format&fit=crop&w=800&q=90"],
    description: "The Puzzle bag is a feat of Spanish craftsmanship — 35 geometrically-cut leather pieces folded together without a single visible seam.",
    details: [
      "Natural calfskin leather",
      "35 individually cut pieces",
      "Anagram brass clasp",
      "Detachable strap",
      "Made in Spain",
    ],
    rating: 4.9,
    reviews: 4890,
    inStock: 3,
  },
  {
    id: "celine-triomphe",
    name: "Triomphe Canvas Bag",
    brand: "Céline",
    price: 2_85_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1463702049690-28f569230a36?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1463702049690-28f569230a36?auto=format&fit=crop&w=800&q=90"],
    description: "The Triomphe canvas is Céline's most recognisable archive print. Revived by Hedi Slimane, it became the coolest bag of the decade.",
    details: [
      "Triomphe canvas",
      "Natural calfskin trim",
      "Gold-finish hardware",
      "Zip closure",
      "Made in Italy",
    ],
    rating: 4.8,
    reviews: 6103,
    inStock: 6,
  },
  {
    id: "hermes-himalayan-birkin",
    name: "Himalayan Niloticus Birkin 25",
    brand: "Hermès",
    price: 1_42_50_000,
    category: "leather-goods",
    image: "https://images.unsplash.com/photo-1610516014366-cb565edfd36f?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1610516014366-cb565edfd36f?auto=format&fit=crop&w=800&q=90"],
    description: "The most coveted object in the known universe. The Himalayan Birkin in gradient white Niloticus crocodile skin with diamond-set white gold hardware. This bag has sold for $450,000 at Christie's. The universe charges a tax when you acquire this one.",
    details: [
      "Niloticus crocodile leather — gradient white",
      "18K white gold hardware",
      "Diamond-set lock and hardware",
      "Handcrafted over 48 hours by a single artisan",
      "Christie's auction record: $450,000",
    ],
    rating: 5.0,
    reviews: 7,
    inStock: 1,
    badge: "The Holy Grail",
    exclusive: true,
    cursed: true,
  },

  // ── AUTOMOBILES ────────────────────────────────────────────────────────────
  {
    id: "lamborghini-huracan",
    name: "Huracán EVO",
    brand: "Lamborghini",
    price: 2_72_65_000,
    category: "automobiles",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=90",
    images: [
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=90",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=90",
    ],
    description: "The Huracán EVO represents the next step in the evolution of the V10-powered supercar. Visceral, precise, beautiful.",
    details: [
      "5.2L V10, 640 CV",
      "0–100 km/h in 2.9 seconds",
      "Top speed: 325 km/h",
      "All-wheel drive",
      "LDVI intelligent drive system",
    ],
    rating: 4.9,
    reviews: 342,
    inStock: 2,
    badge: "Limited Allocation",
  },
  {
    id: "bugatti-chiron",
    name: "Chiron Super Sport",
    brand: "Bugatti",
    price: 37_05_00_000,
    category: "automobiles",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=90"],
    description: "Beyond the notion of speed itself. The Chiron Super Sport is the most powerful, fastest and most exclusive production car in history.",
    details: [
      "8.0L W16 quad-turbocharged",
      "1,600 horsepower",
      "Top speed: 440 km/h",
      "0–100 km/h in 2.3 seconds",
      "1 of 60 units worldwide",
    ],
    rating: 5.0,
    reviews: 89,
    inStock: 1,
    badge: "1 of 60",
    exclusive: true,
    cursed: true,
  },
  {
    id: "ferrari-sf90",
    name: "SF90 Stradale",
    brand: "Ferrari",
    price: 5_93_75_000,
    category: "automobiles",
    image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=800&q=90"],
    description: "Ferrari's most powerful road car. A hybrid masterpiece blending tradition with the most advanced technology.",
    details: [
      "3.9L V8 twin-turbo + 3 electric motors",
      "1,000 CV total output",
      "0–100 km/h in 2.5 seconds",
      "Top speed: 340 km/h",
      "eManettino driving modes",
    ],
    rating: 4.9,
    reviews: 217,
    inStock: 3,
  },
  {
    id: "rolls-royce-phantom",
    name: "Phantom VIII Extended",
    brand: "Rolls-Royce",
    price: 5_70_00_000,
    category: "automobiles",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=90"],
    description: "The pinnacle of automotive luxury. The Phantom commands the road with near-silence, the finest leathers, and a starlight headliner of 1,344 hand-stitched fibre optics.",
    details: [
      "6.75L twin-turbo V12, 563 bhp",
      "Starlight headliner — 1,344 fibre optics",
      "Gallery dashboard — bespoke art installation",
      "Magic carpet ride suspension",
      "Spirit of Ecstasy in stainless steel",
    ],
    rating: 5.0,
    reviews: 142,
    inStock: 2,
    badge: "The Spirit of Ecstasy",
    exclusive: true,
  },
  {
    id: "mclaren-720s",
    name: "720S Spider",
    brand: "McLaren",
    price: 2_56_50_000,
    category: "automobiles",
    image: "https://images.unsplash.com/photo-1580274455191-1c62238fa1c9?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1580274455191-1c62238fa1c9?auto=format&fit=crop&w=800&q=90"],
    description: "720 metric horsepower. Open-top freedom. The McLaren 720S Spider is the most thrilling open-top supercar ever built.",
    details: [
      "4.0L twin-turbo V8, 720PS",
      "0–100 km/h in 2.9 seconds",
      "Top speed: 341 km/h",
      "Carbon fibre MonoCell II-T chassis",
      "Retractable hardtop in 11 seconds",
    ],
    rating: 4.9,
    reviews: 198,
    inStock: 2,
    badge: "Carbon Fibre Monocell",
  },
  {
    id: "porsche-911-turbo",
    name: "911 Turbo S",
    brand: "Porsche",
    price: 2_47_00_000,
    category: "automobiles",
    image: "https://images.unsplash.com/photo-1617531653332-bd46c16f4d68?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1617531653332-bd46c16f4d68?auto=format&fit=crop&w=800&q=90"],
    description: "The definitive 911. The Turbo S fuses everyday usability with supercar performance — because Porsche believes you shouldn't have to choose.",
    details: [
      "3.8L flat-six twin-turbo, 650 PS",
      "0–100 km/h in 2.7 seconds",
      "Top speed: 330 km/h",
      "All-wheel drive with rear-wheel steering",
      "PDCC Sport anti-roll system",
    ],
    rating: 4.9,
    reviews: 421,
    inStock: 3,
    badge: "992 Generation",
  },

  // ── JEWELRY ────────────────────────────────────────────────────────────────
  {
    id: "cartier-diamond-necklace",
    name: "Panthère de Cartier",
    brand: "Cartier",
    price: 49_40_000,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=90",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=90",
    ],
    description: "An icon since 1914. The Panthère embodies the free and independent spirit of Cartier in white gold and diamonds.",
    details: [
      "18K white gold",
      "3.2ct diamond pavé",
      "Onyx and tsavorite accent stones",
      "Handcrafted in Geneva",
      "Cartier leather case included",
    ],
    rating: 5.0,
    reviews: 1876,
    inStock: 2,
    badge: "Heirloom Piece",
    exclusive: true,
  },
  {
    id: "tiffany-diamond-ring",
    name: "Tiffany Setting® Ring",
    brand: "Tiffany & Co.",
    price: 36_57_500,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=90"],
    description: "The most famous engagement ring in the world. Invented by Charles Lewis Tiffany in 1886, still defining elegance today.",
    details: [
      "2.08ct round brilliant diamond",
      "VS1 clarity, G color",
      "Platinum band",
      "GIA certified",
      "Tiffany Blue Box® included",
    ],
    rating: 5.0,
    reviews: 9341,
    inStock: 5,
  },
  {
    id: "van-cleef-alhambra",
    name: "Vintage Alhambra Necklace",
    brand: "Van Cleef & Arpels",
    price: 11_40_000,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=90"],
    description: "The four-leaf clover motif that has graced royalty since 1968. Fortune, health, love, success — all yours.",
    details: [
      "18K yellow gold",
      "Malachite clover motif",
      "Gold bead border",
      "42cm chain",
      "VCA certificate of authenticity",
    ],
    rating: 5.0,
    reviews: 6780,
    inStock: 2,
    exclusive: true,
    badge: "Iconic Since 1968",
  },
  {
    id: "bulgari-serpenti",
    name: "Serpenti Viper Bracelet",
    brand: "Bulgari",
    price: 18_05_000,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=800&q=90"],
    description: "The Serpenti is Bulgari's most powerful icon. Coiled in diamond-set white gold, it commands every room.",
    details: [
      "18K white gold",
      "Full diamond pavé",
      "Emerald eyes",
      "Coiling serpent design",
      "Bulgari Rome certificate",
    ],
    rating: 5.0,
    reviews: 2341,
    inStock: 1,
    exclusive: true,
  },
  {
    id: "chopard-happy-diamonds",
    name: "Happy Diamonds Icons Bracelet",
    brand: "Chopard",
    price: 9_50_000,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=90"],
    description: "The groundbreaking idea that diamonds should dance freely. In the Chopard Happy Diamonds collection, diamonds float untethered — visibly, joyfully alive.",
    details: [
      "18K rose gold",
      "7 dancing diamond hearts",
      "Round brilliant diamonds",
      "Sapphire crystal panels",
      "Swiss Made",
    ],
    rating: 4.9,
    reviews: 2103,
    inStock: 3,
    badge: "Dancing Diamonds",
  },
  {
    id: "harry-winston-premier",
    name: "Premier Round Brilliant Ring",
    brand: "Harry Winston",
    price: 57_00_000,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1597633125097-5a9961e1f03d?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1597633125097-5a9961e1f03d?auto=format&fit=crop&w=800&q=90"],
    description: "The King of Diamonds. Harry Winston has dressed more Oscar winners than any other jeweller. This Premier ring is the reason why.",
    details: [
      "3.5ct round brilliant diamond",
      "D color, FL clarity",
      "Platinum micro-pavé band",
      "Harry Winston certificate",
      "Salon cut and polished in New York",
    ],
    rating: 5.0,
    reviews: 891,
    inStock: 2,
    exclusive: true,
    badge: "King of Diamonds",
  },
  {
    id: "graff-pink-diamond",
    name: "Graff Pink Diamond Ring",
    brand: "Graff",
    price: 380_00_00_000,
    category: "jewelry",
    image: "https://images.unsplash.com/photo-1652944885843-bba16e56c264?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1652944885843-bba16e56c264?auto=format&fit=crop&w=800&q=90"],
    description: "A 24.78ct Fancy Intense Pink diamond of extraordinary quality. Sold at Sotheby's Geneva for $46 million. Now available for your virtual collection — but the universe always collects its tax.",
    details: [
      "24.78ct Fancy Intense Pink diamond",
      "Type IIa — highest purity",
      "Previously owned by Harry Winston",
      "Sotheby's auction record: $46.2M (2010)",
      "One of the most significant diamonds in existence",
    ],
    rating: 5.0,
    reviews: 3,
    inStock: 1,
    badge: "$46.2M at Sotheby's",
    exclusive: true,
    cursed: true,
  },

  // ── YACHTS & JETS ──────────────────────────────────────────────────────────
  {
    id: "sea-ray-yacht",
    name: "L650 Fly",
    brand: "Sea Ray",
    price: 17_57_50_000,
    category: "yachts",
    image: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=800&q=90"],
    description: "The pinnacle of flybridge yachts. The L650 Fly delivers an unmatched blend of luxury, performance, and style.",
    details: [
      "19.8m (65 ft) LOA",
      "Twin Volvo IPS 1350 engines",
      "3 staterooms, 2 heads",
      "Gourmet galley",
      "Premium Bose sound system",
    ],
    rating: 4.9,
    reviews: 54,
    inStock: 2,
    badge: "2025 Model",
  },
  {
    id: "gulfstream-g700",
    name: "G700 Private Jet",
    brand: "Gulfstream",
    price: 712_50_00_000,
    category: "yachts",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=90"],
    description: "The world's largest purpose-built business jet. Redefining what it means to fly in ultimate luxury.",
    details: [
      "Range: 7,500 nautical miles",
      "Max speed: Mach 0.925",
      "Ultra-long range capability",
      "Dual-zone cabin, seats 19",
      "Advanced Cabin Management System",
    ],
    rating: 5.0,
    reviews: 12,
    inStock: 1,
    badge: "One Remaining",
    exclusive: true,
    cursed: true,
  },
  {
    id: "sunseeker-predator-74",
    name: "Predator 74 Sport Yacht",
    brand: "Sunseeker",
    price: 10_45_00_000,
    category: "yachts",
    image: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=800&q=90"],
    description: "The Sunseeker Predator 74 is the ultimate expression of fast, aggressive luxury on water. Seen in every Bond film worth remembering.",
    details: [
      "22.6m (74 ft) LOA",
      "Twin MAN V12 1,550 hp engines",
      "Top speed: 36 knots",
      "3 cabins, 2 bathrooms",
      "Teak cockpit and sun platform",
    ],
    rating: 4.9,
    reviews: 37,
    inStock: 2,
    badge: "As Seen in Bond Films",
  },
  {
    id: "bombardier-global-7500",
    name: "Global 7500 Business Jet",
    brand: "Bombardier",
    price: 95_00_00_000,
    category: "yachts",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=90"],
    description: "The world's largest and longest-range purpose-built business jet. Four living spaces, a full kitchen, and the range to fly Delhi to New York non-stop.",
    details: [
      "Range: 7,700 nautical miles",
      "Four living spaces, sleeps 10",
      "Mach 0.925 high speed cruise",
      "Full-size kitchen & master suite",
      "Rolls-Royce Pearl 15 engines",
    ],
    rating: 5.0,
    reviews: 9,
    inStock: 1,
    badge: "Longest Range Jet",
    exclusive: true,
  },

  // ── SHOES ──────────────────────────────────────────────────────────────────
  {
    id: "christian-louboutin-so-kate",
    name: "So Kate 120 Pumps",
    brand: "Christian Louboutin",
    price: 95_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=90"],
    description: "The iconic red sole. The So Kate is the most coveted stiletto in the world — razor-thin heel, pointed toe, pure power.",
    details: ["Kid leather upper", "120mm stiletto heel", "Signature red lacquered sole", "Pointed toe", "Made in Italy"],
    rating: 4.9,
    reviews: 11203,
    inStock: 5,
    badge: "Icon",
  },
  {
    id: "gucci-horsebit-loafer",
    name: "Horsebit 1953 Loafer",
    brand: "Gucci",
    price: 76_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=800&q=90"],
    description: "A Gucci archival design reissued since 1953. The gold horsebit detail is the ultimate casual luxury statement.",
    details: ["Leather upper", "Signature gold horsebit", "Leather sole", "Made in Italy", "Available in 6 colourways"],
    rating: 4.8,
    reviews: 6730,
    inStock: 6,
  },
  {
    id: "balenciaga-triple-s",
    name: "Triple S Sneaker",
    brand: "Balenciaga",
    price: 85_500,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=90"],
    description: "The sneaker that redefined bulky footwear as high fashion. Triple-layered sole, unmistakable silhouette.",
    details: ["Mesh & leather upper", "Triple-layer rubber sole", "Leather lining", "Logo embossed insole", "Made in Italy"],
    rating: 4.7,
    reviews: 9841,
    inStock: 7,
  },
  {
    id: "jimmy-choo-azia",
    name: "Azia 95 Crystal Sandal",
    brand: "Jimmy Choo",
    price: 1_14_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=90"],
    description: "Dazzling crystal-embellished straps on a sleek stiletto. Worn on red carpets from Cannes to Mumbai.",
    details: ["Crystal mesh upper", "95mm heel", "Leather lining", "Rubber sole", "Made in Italy"],
    rating: 4.9,
    reviews: 3210,
    inStock: 3,
    badge: "Red Carpet",
    exclusive: true,
  },
  {
    id: "tom-ford-jago",
    name: "Jago Embossed Derby",
    brand: "Tom Ford",
    price: 95_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=90"],
    description: "Quiet luxury perfected. The Jago Derby in crocodile-embossed leather is the shoe for those who know.",
    details: ["Crocodile-embossed calfskin", "Leather sole", "Hand-welted construction", "Made in Italy", "Dust bag included"],
    rating: 4.8,
    reviews: 1540,
    inStock: 4,
  },
  {
    id: "nike-air-jordan-dior",
    name: "Air Jordan 1 × Dior",
    brand: "Dior × Nike",
    price: 3_80_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=800&q=90"],
    description: "The most coveted sneaker collaboration in history. 8,000 pairs. Sold out in 43 seconds. Yours now — virtually.",
    details: ["Oblique canvas upper", "Nike Air cushioning", "Dior logo throughout", "Certificate of authenticity", "1 of 8,000"],
    rating: 5.0,
    reviews: 47210,
    inStock: 1,
    badge: "Sold Out IRL",
    exclusive: true,
  },
  {
    id: "manolo-blahnik-bb",
    name: "BB 105 Suede Pumps",
    brand: "Manolo Blahnik",
    price: 85_500,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1560243563-062bfc001d68?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1560243563-062bfc001d68?auto=format&fit=crop&w=800&q=90"],
    description: "The shoe that launched a thousand declarations of love. Carrie Bradshaw's favourite. The BB pump is the world's most romantic heel.",
    details: ["Satin suede upper", "105mm heel", "Pointed toe", "Leather lining & sole", "Made in Italy"],
    rating: 4.9,
    reviews: 14320,
    inStock: 5,
    badge: "As Worn in SATC",
  },
  {
    id: "john-lobb-william",
    name: "William II Brogue",
    brand: "John Lobb",
    price: 1_14_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=800&q=90"],
    description: "The finest English broguing. The John Lobb William II is handcrafted on the bench by a single craftsman, using leather tanned to a 100-year-old specification.",
    details: ["Calf leather upper", "Hand-stitched welt", "Leather sole", "Bench-made in England", "Wooden shoe trees included"],
    rating: 4.9,
    reviews: 2103,
    inStock: 4,
    badge: "Bespoke Quality",
  },
  {
    id: "valentino-rockstud",
    name: "Rockstud Pump 100mm",
    brand: "Valentino Garavani",
    price: 76_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=90"],
    description: "The stud that started a movement. Valentino's Rockstud has decorated shoes, bags, and red carpets since 2010 and shows no sign of stopping.",
    details: ["Calfskin leather", "Metallic rockstud trim", "100mm tapered heel", "Leather sole", "Made in Italy"],
    rating: 4.7,
    reviews: 8901,
    inStock: 6,
  },
  {
    id: "bottega-stretch-mule",
    name: "Stretch Woven Mule",
    brand: "Bottega Veneta",
    price: 90_250,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1515955914813-01ac0e7a3b85?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1515955914813-01ac0e7a3b85?auto=format&fit=crop&w=800&q=90"],
    description: "The slide that broke the internet — twice. Bottega Veneta's intrecciato-woven mule is the chicest way to step into quiet luxury.",
    details: ["Intrecciato lambskin woven upper", "Square toe", "Block heel, 60mm", "Leather lining", "Made in Italy"],
    rating: 4.8,
    reviews: 4560,
    inStock: 5,
  },
  {
    id: "yeezy-red-october",
    name: 'Air Yeezy 2 "Red October"',
    brand: "Nike × Ye",
    price: 3_80_000,
    category: "shoes",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=90",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=90"],
    description: "The most cursed sneaker in history. Never officially released. Dropped without warning at 3:14am. Currently resells for $10,000+. Owning this virtually means you've inherited the chaos.",
    details: [
      "Full red nubuck upper",
      "Glow-in-the-dark sole",
      "Officially: never released publicly",
      "Resale value: ₹10L+ and climbing",
      "Comes with all the Ye-energy. You've been warned.",
    ],
    rating: 5.0,
    reviews: 666,
    inStock: 1,
    badge: "Never Released Publicly",
    exclusive: true,
    cursed: true,
  },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: Category): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

// All prices stored in INR
export function formatPrice(price: number): string {
  if (price >= 1_00_00_00_000) {
    return `₹${(price / 1_00_00_00_000).toFixed(2)} Cr`;
  }
  if (price >= 1_00_00_000) {
    return `₹${(price / 1_00_00_000).toFixed(2)} Cr`;
  }
  if (price >= 1_00_000) {
    return `₹${(price / 1_00_000).toFixed(1)} L`;
  }
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}
